# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f9c1c648ec1bfd6aa189787be2559c1ba34b83a32ae2b777b802eb5af859af30fc67b0696a21bf6f60dafd16f4e3b84c0ff5f9735278d2376d92fa3709c792

test:
  secret_key_base: 63a0ccff078962354663f663233ccc2322c303d9128d52569ca3b87507e60143fe1350819384d4d604b6e6423c6a0161a3d6ca74def498778c8a387d84151f97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
